version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/projectnexus-frontend:latest
    ports:
      - "3050:3050"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NODE_ENV=production
      - PORT=3050
      - HOSTNAME=0.0.0.0
    networks:
      - projectnexus-network
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/projectnexus-backend:latest
    ports:
      - "8085:8085"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8085
      - GIN_MODE=release
    depends_on:
      - mongodb
    networks:
      - projectnexus-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - projectnexus-network
    restart: unless-stopped

networks:
  projectnexus-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local