services:
  frontend:
    image: projectnexus-frontend:latest
    ports:
      - "3050:3050"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - projectnexus-network

  backend:
    image: projectnexus-backend:latest
    ports:
      - "8085:8085"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - projectnexus-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - projectnexus-network

networks:
  projectnexus-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local