name: ProjectNexus CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: testpassword
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to start..."
          sleep 30

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      
      # Build backend
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Backend
        working-directory: ./backend
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build -o projectnexus-api ./cmd/api
      
      # Build frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm ci
          ls -la

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm run build
          ls -la
          ls -la .next || echo ".next directory not found"
      
      # Upload artifacts
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/projectnexus-api
          retention-days: 1

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            frontend/.next/**/*
            frontend/package.json
            frontend/package-lock.json
            docker-compose.yml
            docker-compose.dev.yml
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: ./backend-build

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build

      - name: Debug Local Files
        run: |
          pwd
          echo "Current directory structure:"
          find . -type f
          echo "Backend files:"
          ls -la backend-build/
          echo "Frontend files:"
          ls -la frontend-build/

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          source: "backend-build/projectnexus-api,frontend-build/,docker-compose*.yml"
          target: "~/projectnexus/temp/"
          strip_components: 1

      - name: Setup and Start Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          command_timeout: "20m"
          script: |
            echo "Setting up project structure..."
            mkdir -p ~/projectnexus/{backend,frontend}
            
            echo "Moving backend files..."
            cp ~/projectnexus/temp/projectnexus-api ~/projectnexus/backend/
            chmod +x ~/projectnexus/backend/projectnexus-api
            
            echo "Moving frontend files..."
            if [ -d ~/projectnexus/temp/.next ]; then
              cp -r ~/projectnexus/temp/.next ~/projectnexus/frontend/
            else
              echo "Warning: .next directory not found"
              ls -la ~/projectnexus/temp/
            fi
            
            cp ~/projectnexus/temp/package*.json ~/projectnexus/frontend/
            cp ~/projectnexus/temp/docker-compose*.yml ~/projectnexus/
            
            echo "Installing frontend dependencies..."
            cd ~/projectnexus/frontend
            npm ci --production
            
            echo "Updating environment variables..."
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env
            
            echo "Copying Docker files..."
            cd ~/projectnexus
            chmod +x backend/projectnexus-api
            
            echo "Checking Docker Compose files..."
            ls -la docker-compose*.yml
            
            echo "Starting services..."
            docker compose -f docker-compose.yml -f docker-compose.dev.yml down || true
            docker compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache
            docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d