name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          tags: projectnexus-frontend:latest

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true
          tags: projectnexus-backend:latest
          no-cache: true

      - name: Save frontend image as tar archive
        run: docker save -o frontend.tar projectnexus-frontend:latest

      - name: Save backend image as tar archive
        run: docker save -o backend.tar projectnexus-backend:latest

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          # Create .env file
          cat > .env << 'EOL'
          MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
          JWT_SECRET=${JWT_SECRET}
          NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
          EOL
          
          # Create mongo-init.js file
          cat > mongo-init.js << 'EOL'
          db = db.getSiblingDB('admin');

          // Create root user (if not exists)
          db.createUser({
              user: "root",
              pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
              roles: [ { role: "root", db: "admin" } ]
          });

          db = db.getSiblingDB('projectnexus');

          // Create application database and user
          db.createUser({
              user: "projectnexus",
              pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
              roles: [{ role: "readWrite", db: "projectnexus" }]
          });

          // Create indexes for better performance
          db.users.createIndex({ "email": 1 }, { unique: true });
          db.projects.createIndex({ "created_by": 1 });
          db.documents.createIndex({ "project_id": 1 });
          EOL
          
          # Check if files were created correctly
          ls -la .env mongo-init.js
          
          # Transfer files individually with explicit paths
          echo "Copying frontend image..."
          scp frontend.tar $DEPLOY_USER@$DEPLOY_HOST:~/frontend.tar
          
          echo "Copying backend image..."
          scp backend.tar $DEPLOY_USER@$DEPLOY_HOST:~/backend.tar
          
          echo "Copying docker-compose.yml..."
          scp docker-compose.yml $DEPLOY_USER@$DEPLOY_HOST:~/docker-compose.yml
          
          echo "Copying mongo-init.js..."
          scp mongo-init.js $DEPLOY_USER@$DEPLOY_HOST:~/mongo-init.js
          
          echo "Copying .env..."
          scp .env $DEPLOY_USER@$DEPLOY_HOST:~/.env
          
          # Deploy
          ssh $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            # Verify files exist and are correct
            ls -la ~/mongo-init.js ~/.env
          
            # Load images
            docker load -i ~/frontend.tar
            docker load -i ~/backend.tar
          
            # Stop existing containers and clean up volumes
            docker-compose down --volumes --remove-orphans
          
            # Start services
            docker-compose up -d
          
            # Clean up
            docker image prune -f
            rm ~/frontend.tar ~/backend.tar
          EOF
